---
version: '3.1'

services:
  range-db:
    image: postgres:10.6
    restart: always
    environment:
      - POSTGRES_USER=rangeuser
      - POSTGRES_PASSWORD=range123
      - POSTGRES_DB=rangedb
    ports:
      - 5432:5432

  range-service:
    env_file:
      - .env.default
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3002:3000
    links:
      - range-db
    # volumes:
    #   - ./:/usr/src/service:cached
    command: yarn start:dev

  localstack:
    image: localstack/localstack
    ports:
      - '4566-4584:4566-4584'
      - '8081:8080'
    environment:
      SERVICES: sqs,s3
      DEFAULT_REGION: ap-southeast-2
      DEBUG: 1
      # DATA_DIR: /tmp/localstack/data
      # DOCKER_HOST: unix:///var/run/docker.sock
    # volumes:
    #   - '/var/run/docker.sock:/var/run/docker.sock'
    #   - '/tmp/localstack:/tmp/localstack'
